apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  generateName: start-workflow-<git_repo_name>-
spec:
  serviceAccountName: argo
  entrypoint: start-workflow
  arguments:
    parameters:
    - name: repo
      value: <git_repo_full>
    - name: revision
      value: <git_revision>
  templates:
  - name: start-workflow
    inputs:
      artifacts:
      - name: git-repo
        path: /src
        git:
          repo: "{{workflow.parameters.repo}}"
          revision: "{{workflow.parameters.revision}}"
          usernameSecret:
            name: bitbucket-argo
            key: username
          passwordSecret:
            name: bitbucket-argo
            key: password
    metadata:
      labels:
        app: argo
    container:
      resources: 
        requests:
          cpu: 50m
          memory: 50Mi
        limits: 
          cpu: 100m
          memory: 100Mi
      image: argoproj/argocli
      args: ["submit", "src/argo.yml"]
 
  